config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'products/index'
  devise_for :users
  
  get '/shopping_cart', to: 'orders#index', as: 'orders'
  resources :products, only: [:index] do
    resources :orders, only: [:create] 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orders
    has_many :users, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :products, through: :orders
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = Order.where({
      payed: false,
      user_id: current_user.id
    })
  end
  def create
    order = Order.new({
      product_id: params[:product_id],
      user_id: current_user.id 
    })
    order.save
    redirect_to products_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carrito</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/litera/bootstrap.min.css" rel="stylesheet" integrity="sha384-D/7uAka7uwterkSxa2LwZR7RJqH2X6jfmhkJ0vFPGUtPyBMF2WMq9S+f9Ik5jJu1" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </div>
  </body>
</html>

app/views/orders/index.html.erb
<% @orders.each do |order| %>
<%= order.product.name %>
<%= order.product.price %>
<%= order.payed %>
<% end %>

<% sum= 0 %>
<% @orders.each do |order| %>
<% sum += order.product.price %>
<% end %>

Total: <%= sum %>

app/views/products/index.html.erb
<%= link_to 'Ver carrito de compra', orders_path %>
<%= link_to 'Cerrar sesión', destroy_user_session_path %>

<% @products.each_slice(3) do |products| %>
<div class='row'>
    <% products.each do |product| %>
        <div class='card m-2' style="width: 30%;"> 
        <%= image_tag product.photo, class: 'card-img-top' %>
            <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= product.price %></h6>
            <%= button_to 'Comprar', product_orders_path(product), class:'btn btn-primary' %>
            </div>
        </div>
    <% end %>
    </div>
<% end %>